# Generated by Django 3.2.5 on 2021-07-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscription',
        ),
        migrations.RenameModel(
            old_name='UserSubscribe',
            new_name='UserSubscription',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscribe',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_of_bookmarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_of_subs',
        ),
    ]
