# Generated by Django 3.2.5 on 2021-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_time',
            field=models.DateTimeField(null=True),
        ),
    ]
