# Generated by Django 3.2.5 on 2021-07-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210712_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user'),
        ),
    ]
