# Generated by Django 3.2.5 on 2021-07-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210712_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='label_id',
            field=models.CharField(default='Label_6', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
