# Generated by Django 3.2.5 on 2021-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bookmark_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='label_id',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='email_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
