# Generated by Django 3.2.5 on 2021-07-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210718_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_email_time',
        ),
    ]
